name: Build
on:
  push:
    branches: [master]

env:
  LIBRARY_PATH: addons/godot-wasm/bin
  WASMER_VERSION: '2.3.0'

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt -y install build-essential pkg-config libx11-dev libxcursor-dev \
            libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev \
            libudev-dev libxi-dev libxrandr-dev yasm

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Packages
        run: python -m pip install scons

      - name: Download Wasmer Library
        run: |
          mkdir ${{ github.workspace }}/wasmer
          wget -c https://github.com/wasmerio/wasmer/releases/download/${{ env.WASMER_VERSION }}/wasmer-linux-musl-amd64.tar.gz -O - | tar -xz -C wasmer

      - name: Submodule Hash
        run: echo "SUBMODULE_HASH=$( git rev-parse HEAD:godot-cpp )" >> $GITHUB_ENV

      - name: Cache Godot Library
        id: cache-godot-cpp
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/godot-cpp/bin
            ${{ github.workspace }}/godot-cpp/include
            ${{ github.workspace }}/godot-cpp/godot-headers/**/*.h
          key: ${{ runner.os }}-${{ env.SUBMODULE_HASH }}-${{ secrets.GODOT_CPP_CACHE_VERSION }}

      - name: Compile Godot Library
        if: steps.cache-godot-cpp.outputs.cache-hit != 'true'
        run: |
          cd ${{ github.workspace }}/godot-cpp
          scons platform=linux target=release generate_bindings=yes -j4

      - name: Compile Addon
        run: scons platform=linux target=release

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: ${{ github.workspace }}/${{ env.LIBRARY_PATH }}/linux
          if-no-files-found: error

  build-osx:
    name: Build OSX
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Packages
        run: python -m pip install scons

      - name: Universal Wasmer Library
        run: |
          mkdir ${{ github.workspace }}/wasmer
          wget -c https://github.com/wasmerio/wasmer/releases/download/${{ env.WASMER_VERSION }}/wasmer-darwin-amd64.tar.gz -O - | tar -xz -C wasmer-amd64
          mv ${{ github.workspace }}/wasmer/lib/libwasmer.dylib ${{ github.workspace }}/wasmer/lib/libwasmer-amd64.dylib
          wget -c https://github.com/wasmerio/wasmer/releases/download/${{ env.WASMER_VERSION }}/wasmer-darwin-arm64.tar.gz -O - | tar -xz -C wasmer-arm64
          mv ${{ github.workspace }}/wasmer/lib/libwasmer.dylib ${{ github.workspace }}/wasmer/lib/libwasmer-arm64.dylib
          lipo ${{ github.workspace }}/wasmer/lib/libwasmer*.dylib -output ${{ github.workspace }}/wasmer/lib/libwasmer.dylib -create

      - name: Submodule Hash
        run: echo "SUBMODULE_HASH=$( git rev-parse HEAD:godot-cpp )" >> $GITHUB_ENV

      - name: Cache Godot Library
        id: cache-godot-cpp
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/godot-cpp/bin
            ${{ github.workspace }}/godot-cpp/include
            ${{ github.workspace }}/godot-cpp/godot-headers/**/*.h
          key: ${{ runner.os }}-${{ env.SUBMODULE_HASH }}-${{ secrets.GODOT_CPP_CACHE_VERSION }}

      - name: Compile Godot Library
        if: steps.cache-godot-cpp.outputs.cache-hit != 'true'
        run: |
          cd ${{ github.workspace }}/godot-cpp
          scons platform=osx target=release generate_bindings=yes -j4

      - name: Compile Addon
        run: scons platform=osx target=release

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: osx
          path: ${{ github.workspace }}/${{ env.LIBRARY_PATH }}/osx
          if-no-files-found: error
