name: Release
on:
  push:
    tags: [v*]

env:
  LIBRARY_PATH: addons/godot-wasm/bin
  RELEASE_ASSET: godot-wasm.zip

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for stefanzweifel/git-auto-commit-action@v4
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clean Binaries
        run: rm -rf ${{ github.workspace }}/${{ env.LIBRARY_PATH }}

      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          commit: ${{ github.sha }}
          path: ${{ github.workspace }}/${{ env.LIBRARY_PATH }}

      - name: Prepare Asset
        run: |
          cd ${{ github.workspace }}
          zip -r ${{ env.RELEASE_ASSET }} addons

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/${{ env.RELEASE_ASSET }}

      - name: Stash Changes
        run: git stash

      - name: Checkout Asset Library Branch
        uses: actions/checkout@v3
        with:
          ref: asset-library

      - name: Apply Stash
        run: git checkout stash -- addons

      - name: Push Asset Library Branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ github.sha }}